apiVersion: apps/v1
kind: Deployment
metadata:
  name: rig-and-barter-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rig-and-barter-frontend
  template:
    metadata:
      labels:
        app: rig-and-barter-frontend
    spec:
      containers:
        - name: rig-and-barter-frontend
          image: cjshore1996/dev-rig-and-barter-frontend:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: rig-and-barter-frontend
spec:
  # type: NodePort  # Expose the service on a static port on each node
  selector:
    app: rig-and-barter-frontend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 80

# TODO:
# - Create a loadbalancer (i.e MetalLB) and nginx-ingress or trafik or something to createa ingress controllers
# - Then make web alls through the loadbalancer/ingress controller to access the frontend/backend

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
#   name: rewrite-example
#   namespace: default
# spec:
#   ingressClassName: nginx
#   rules:
#   - http:
#       paths:
#       - path: /()(.*)
#         pathType: Prefix
#         backend:
#           service:
#             name: rig-and-barter-frontend
#             port: 
#               number: 80
#       - path: /api(/|$)(.*)
#         pathType: Prefix
#         backend:
#           service:
#             name: api-gateway
#             port: 
#               number: 9000