name: Clean Frontend Deployment 

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - demo
        - prod

jobs:
  clean-deployment-frontend:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - uses: actions-hub/kubectl@master
      name: Clean Frontend Deployement
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: delete -f k8s/${{ inputs.environment }}/rig-and-barter-frontend.yaml