name: Deploy Frontend To Kubernetes

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - demo
        - prod
      replicas:
        description: 'Replicas'
        required: true
        default: '1'
        type: number

jobs:
  deploy-frontend:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Insert Replica Count on Deployment
      run: |
        sed -i "s/__REPLICAS__/${{ inputs.replicas }}/g" k8s/${{ inputs.environment }}/rig-and-barter-frontend.yaml

    - uses: actions-hub/kubectl@master
      name: Deploy Frontend
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f k8s/${{ inputs.environment }}/rig-and-barter-frontend.yaml