name: Publish Frontend Development Image

on:
  push:
    branches: [ "buildTest" ]
  pull_request:
    branches: [ "main" ]
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    env:
      AccountId: 'cjshore1996'
      ImageName: 'rig-and-barter-frontend'
      Version: 'latest'
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t dev-$ImageName .
    - name: Tag the image
      run: docker tag dev-$ImageName:$Version $AccountId/dev-$ImageName:$Version
    - name: Push the image
      run: docker push $AccountId/dev-$ImageName:$Version
