name: Publish Frontend Development Image

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed

jobs:
  publish-image:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    env:
      AccountId: ${{ vars.DOCKER_USERNAME }}
      ImageName: 'rig-and-barter-frontend'
      Version: 'latest'
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Build the Docker image
      run: docker build -t dev-$ImageName .
      
    - name: Tag the image
      run: docker tag dev-$ImageName:$Version $AccountId/dev-$ImageName:$Version
      
    - name: Push the image
      run: docker push $AccountId/dev-$ImageName:$Version
